version: 2.1

orbs:
  android: circleci/android@3.1.0
#  gcp-cli: circleci/gcp-cli@3.3.1

# Reusable commands / repeat tasks
commands:
  export_google_services_key:
    steps:
      - run:
          name: Export Google Services key environment variable
          command: echo 'export GOOGLE_SERVICES_JSON="$GOOGLE_SERVICES_JSON"' >> $BASH_ENV

  decode_google_services_key:
    steps:
      - run:
          name: Decode Google Services JSON key
          command: |
            sudo chmod 600 /root/.
            sudo mkdir -m 0755 -p app/src/mock/
            sudo mkdir -m 0755 -p app/src/prod/
            sudo touch -m 0755 app/google-services.json
            sudo touch -m 0755 app/src/mock/google-services.json
            sudo touch -m 0755 app/src/prod/google-services.json
            sudo chmod 777 app/google-services.json
            sudo chmod 777 app/src/mock/google-services.json
            sudo chmod 777 app/src/prod/google-services.json
            sudo echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
            sudo echo $GOOGLE_SERVICES_JSON | base64 --decode > app/src/mock/google-services.json
            sudo echo $GOOGLE_SERVICES_JSON | base64 --decode > app/src/prod/google-services.json
      - run: ls -l app/google-services.json

  export_keystore_key:
    steps:
      - run:
          name: Set the KEYSTORE environment variable to it’s location.
          command: echo 'export KEYSTORE=~/project/keystores/keystore.jks' >> $BASH_ENV
      - run: ls -l ~/project/keystores/keystore.jks

  decode_keystore_key:
    steps:
      - run:
          name: Decode the base64 encoded text back into the keystore.jks file
          command: |
            sudo mkdir -m 0755 -p ~/project/keystores/
            sudo chmod 777 ~/project/keystores/
            echo $ENCODED_KEYSTORE | base64 --decode >> ~/project/keystores/keystore.jks
      - run: ls -l ~/project/keystores/keystore.jks

  save_gradle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-{{ checksum "build.gradle" }}

  restore_gradle_cache:
    steps:
      - restore_cache:
          keys:
            - v1-gradle-{{ checksum "build.gradle" }}


jobs:
  #  use-gcp:
  #    executor: gcp-cli/default
  #    steps:
  #      - gcp-cli/setup:
  #          version: 404.0.0

  quality_check:
    executor:
      name: android/android_machine
      tag: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: ls -l
      - export_google_services_key
      - decode_google_services_key
      - restore_gradle_cache
      - run: ./gradlew dependencies --warning-mode all
      - run: ./gradlew checkstyle pmd lint --warning-mode all
      - save_gradle_cache


  android_tests:
    executor:
      name: android/android_machine
      tag: default
    parallelism: 4
    environment:
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 120 # seconds to wait before killing emu
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: ls -l
      - export_google_services_key
      - decode_google_services_key
      - restore_gradle_cache
      - run:
          name: Installing emulator and Running Instrumentation tests
          command: |
            sdkmanager "platform-tools" "platforms;android-34" "build-tools;30.0.0" "emulator"
            sdkmanager "system-images;android-34;google_apis;x86_64"
            sdkmanager --update
            sdkmanager "emulator" "platform-tools"
            echo no | avdmanager create avd -n test-emulator -k  "system-images;android-34;google_apis;x86_64"
            emulator -avd test-emulator -no-window -no-audio -no-boot-anim -accel on -gpu swiftshader_indirect -metrics-collection &
            adb wait-for-device
            until adb shell getprop sys.boot_completed | grep 1; do sleep 3; done;
            adb shell wm dismiss-keyguard
            sleep 1
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0
            ./gradlew :app:connectedMockDebugAndroidTest --stacktrace --warning-mode all && pkill -SIGTERM crashpad_handler || true, sleep 5, pkill -SIGKILL crashpad_handler || true
      - when:
          condition: false
          steps:
            - run:
                command: circleci-agent step halt
      - run: ls -l app/build/outputs/androidTest-results/ && pwd
      - store_test_results:
          path: app/build/outputs/androidTest-results
      - store_artifacts:
          path: app/build/outputs/androidTest-results
      - save_gradle_cache


  unit_tests:
    executor:
      name: android/android_machine
      tag: default
    parallelism: 4
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: ls -l
      - export_google_services_key
      - decode_google_services_key
      - restore_gradle_cache
      - run: ./gradlew dependencies --warning-mode all
      - android/run_tests:
          test_command: ./gradlew :app:testMockDebugUnitTest --warning-mode all | circleci tests glob "app/src/test/**/*Test.kt" | circleci tests run --command="echo" --verbose --split-by=timings --timings-type=classname
#      - persist_to_workspace:
#          root: ~/project
#          paths:
#            - app/build/
      - run: ls -l app/build/test-results/ && pwd
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/test-results
#      - run:
#          name: Save test results
#          command: |
#            sudo mkdir -m 0755 -p ~/test-results/junit/
#            sudo chmod 777 ~/test-results/junit/
#            find . -type f -regex "app/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
#          when: always
#      - run: ls -l ~/test-results/junit/
#      - store_test_results:
#          path: ~/test-results
#      - store_artifacts:
#          path: ~/test-results/junit
      - save_gradle_cache


  jacoco_code_coverage:
    executor:
      name: android/android_machine
      tag: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: ls -l
      - export_google_services_key
      - decode_google_services_key
      - restore_gradle_cache
      - run: ./gradlew dependencies --warning-mode all
      - run:
          name: Code Climate Test Setup
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Generate JaCoCo report
          command: ./gradlew jacocoTestReport --stacktrace --warning-mode all
      - run: ls -l app/build/reports/jacocoTestReport
      - run:
          name: Upload coverage to code climate
          command: |
            export JACOCO_SOURCE_PATH=app/src/main/java
            ./cc-test-reporter format-coverage app/build/reports/jacocoTestReport/jacocoTestReport.xml --input-type jacoco
            ./cc-test-reporter upload-coverage
      - store_artifacts:
          path: app/build/reports/
          destination: /reports/
      - save_gradle_cache


  release_build:
    executor:
      name: android/android_machine
      tag: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: ls -l
      - export_google_services_key
      - decode_google_services_key
      - decode_keystore_key
      - export_keystore_key
      - restore_gradle_cache
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease --stacktrace --warning-mode all
      - run: ls -l app/
      - store_artifacts:
          path: app/prod/release/app-prod-release.apk
      - save_gradle_cache


workflows:
  build_test_deploy:
    jobs:
      - quality_check
      - android_tests:
          requires:
            - quality_check
      - unit_tests:
          requires:
            - android_tests
      - jacoco_code_coverage:
          requires:
            - unit_tests
      - release_build:
          requires:
            - jacoco_code_coverage

#  install_and_configure_cli:
#    jobs:
#      - use-gcp:
#          context: myContext
