buildscript {
    repositories {
        mavenCentral()
        maven { url = "https://plugins.gradle.org/m2/" }
        maven { url = 'https://maven.google.com/' }
        google()
    }

    dependencies {
        // Add dependency for the Android Gradle Plugin (AGP) version here if needed
    }
}

plugins {
    id("com.android.application")
    id("kotlin-android")
    id("kotlin-parcelize")
    id("jacoco")
    id("com.google.gms.google-services")
    id("org.jetbrains.kotlin.plugin.compose")
}

apply from: rootProject.file('quality/quality.gradle')
apply from: rootProject.file('app/jacoco.gradle')

jacoco {
    toolVersion = "${rootProject.jacocoVersion}"
    reportsDirectory = file("${buildDir}/reports")
}

tasks.withType(Test).configureEach {
    testLogging {
        exceptionFormat = 'full'
        events("passed", "skipped", "failed")
        showStackTraces = true
    }
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ['jdk.internal.*']
    finalizedBy jacocoTestReport
}

android {
    namespace = "com.rwothoromo.devfinder"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.rwothoromo.devfinder"
        minSdk = 23
        targetSdk = 35
        versionCode = 3
        versionName = "1.0.3"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        // The app's state will be completely cleared between tests.
        testInstrumentationRunnerArguments clearPackageData: 'true'
        multiDexEnabled = true
    }

    signingConfigs {
        release {
            try {
                // keystorePropertiesFile - Useful on local machine
                def keystorePropertiesFile = rootProject.file("keystores/keystore.properties")
                def keystoreProperties = new Properties()
                keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

                // System.getenv - Useful on Circle CI
                storeFile = file(keystoreProperties['storeFile'])
                storePassword = keystoreProperties['storePassword']
                keyAlias = keystoreProperties['keyAlias']
                keyPassword = keystoreProperties['keyPassword']
            } catch (Exception e) {
                println("keystorePropertiesFile Error: $e")

                // System.getenv - Useful on Circle CI
                storeFile = file(System.getenv("KEYSTORE") ?: "../keystores/keystore.jks")
                storePassword = System.getenv("KEYSTORE_PASSWORD")
                keyAlias = System.getenv("KEY_ALIAS")
                keyPassword = System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled = true
            signingConfig = signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // Ensure coverage is only collected during debug builds for typical use
            enableUnitTestCoverage = false
            enableAndroidTestCoverage = false
        }
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
            // Setting `minifyEnabled = false` is the default for debug
            // Set coverage to true for debug builds (which is standard)
            enableUnitTestCoverage = true
            enableAndroidTestCoverage = true
        }
    }

    testOptions {
        animationsDisabled = true
        unitTests.includeAndroidResources = true
        unitTests.returnDefaultValues = true
        unitTests.all {
            jacoco {
                includeNoLocationClasses = true
                // Include all classes for coverage, unit tests are optimized for coverage reporting
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.10"
    }

    lint {
        abortOnError = false
    }

    packaging {
        resources {
            // Exclude *.file_extension pattern
            excludes.add("*.md")
            excludes.add("*.html")
            excludes.add("*Test.kt")

            // Exclude all files within a specific folder
            excludes.add("docs/**")

            // Exclude files matching a pattern within a folder
            excludes.add("docs/*.md")
            excludes.add("docs/*.html")
            excludes.add("app/src/test/*.kt")
        }
    }

}

// For toolchain setup (Gradle 7.6+)
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    // 1. Local Files
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    // 2. Kotlin
    implementation(libs.kotlin.stdlib.jdk7)
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:${rootProject.ktxCoroutinesCore}")

    // 3. AndroidX and UI Libraries
    implementation(libs.androidx.constraintlayout)
    implementation(libs.material)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.swiperefreshlayout)
    implementation("androidx.compose.runtime:runtime:$composeVersion")

    // 4. Networking, Serialization, and Images
    implementation(libs.retrofit)
    implementation(libs.gson)
    implementation(libs.converter.gson)
    implementation(libs.logging.interceptor)
    implementation(libs.glide)

    // 5. Firebase
    implementation(platform("com.google.firebase:firebase-bom:$firebaseBom"))
    implementation(libs.firebase.perf)
    implementation(libs.firebase.analytics)
    implementation libs.androidx.espresso.idling.resource
    
    // Explicitly specify protobuf version to resolve conflict in Firebase Perf
    implementation(libs.protobuf.javalite)

    // 6. Testing - Local Unit Tests
    testImplementation(libs.junit)
    testImplementation(libs.androidx.core)
    testImplementation("io.mockk:mockk:${rootProject.mockkVersion}")
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.inline)
    testImplementation(libs.mockito.kotlin)
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:${rootProject.ktxCoroutinesTest}")
    testImplementation(libs.mockwebserver) // Used for mocking network requests

    // 7. Testing - Instrumentation Tests (Android Tests)
    androidTestImplementation(libs.androidx.core)
    androidTestImplementation(libs.androidx.core.ktx)
    androidTestImplementation(libs.androidx.runner)
    androidTestImplementation(libs.androidx.rules)
    androidTestImplementation(libs.androidx.junit) {
        exclude group: 'androidx.test', module: 'orchestrator'
    }
    androidTestImplementation(libs.androidx.junit.ktx)
    androidTestImplementation(libs.androidx.truth)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.espresso.contrib)
    androidTestImplementation(libs.androidx.espresso.intents)
    androidTestImplementation(libs.androidx.idling.concurrent) // For concurrent idling resources
    androidTestImplementation(libs.androidx.espresso.idling.resource) // For generic idling resources
}
